In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Pharma_Patient_Dataset_60_Records.xlsx to Pharma_Patient_Dataset_60_Records (1).xlsx

In [3]:
df = pd.read_excel("Pharma_Patient_Dataset_60_Records.xlsx")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [4]:
print("Number of Rows and Columns:")
print(df.shape)

Number of Rows and Columns:
(60, 15)

In [5]:
df.head()

,Patient ID,Patient\nName,Age,Gender,Disease,Drug\nName,Dosage \nmg,Frequency\nPer Day,Treatment\nDuration Days,Severity \nLevel,Follow \nUp Count,Side \nEffects,Recovery \nRate Percent,Doctor \nRating,Outcome
0,1345002,Ananya,60,Male,Hypertension,Amlodipine,22.5,1,58,Severe,9,No,59,8.3,Not Recovered
1,1345003,Kavya,37,Female,Hypertension,Amlodipine,70.2,2,39,Severe,1,No,82,9.8,Recovered
2,1345004,Ananya,67,Male,Migraine,Topiramate,89.5,2,37,Severe,4,Yes,73,6.3,Improving
3,1345005,Meera,30,Male,Diabetes,Metformin,51.2,2,92,Moderate,8,No,73,5.3,Improving
4,1345006,Ananya,28,Male,Arthritis,Naproxen,17.4,3,47,Moderate,4,Yes,79,6.9,Improving

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient ID               60 non-null     int64
 1   Patient
Name             60 non-null     object
 2   Age                      60 non-null     int64
 3   Gender                   60 non-null     object
 4   Disease                  60 non-null     object
 5   Drug
Name                60 non-null     object
 6   Dosage
mg               60 non-null     float64
 7   Frequency
Per Day        60 non-null     int64
 8   Treatment
Duration Days  60 non-null     int64
 9   Severity
Level          60 non-null     object
 10  Follow
Up Count         60 non-null     int64
 11  Side
Effects            60 non-null     object
 12  Recovery
Rate Percent   60 non-null     int64
 13  Doctor
Rating           60 non-null     float64
 14  Outcome                  60 non-null     object
dtypes: float64(2), int64(6), object(7)
memory usage: 7.2+ KB

In [7]:
print(df.columns)

Index(['Patient ID', 'Patient\nName', 'Age', 'Gender', 'Disease', 'Drug\nName',
       'Dosage \nmg', 'Frequency\nPer Day', 'Treatment\nDuration Days',
       'Severity \nLevel', 'Follow \nUp Count', 'Side \nEffects',
       'Recovery \nRate Percent', 'Doctor \nRating', 'Outcome'],
      dtype='object')

In [8]:
df.isnull().sum()

Patient ID                  0
Patient\nName               0
Age                         0
Gender                      0
Disease                     0
Drug\nName                  0
Dosage \nmg                 0
Frequency\nPer Day          0
Treatment\nDuration Days    0
Severity \nLevel            0
Follow \nUp Count           0
Side \nEffects              0
Recovery \nRate Percent     0
Doctor \nRating             0
Outcome                     0
dtype: int64

In [ ]:
df.describe()

In [9]:
df.describe()

,Patient ID,Age,Dosage \nmg,Frequency\nPer Day,Treatment\nDuration Days,Follow \nUp Count,Recovery \nRate Percent,Doctor \nRating
count,6.000000e+01,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,1.345032e+06,43.650000,53.170000,1.983333,92.433333,4.666667,67.500000,7.630000
std,1.746425e+01,17.000324,29.031434,0.812856,50.301588,3.265986,19.063231,1.470996
min,1.345002e+06,18.000000,2.100000,1.000000,7.000000,1.000000,40.000000,5.100000
25%,1.345017e+06,28.750000,27.150000,1.000000,46.500000,1.000000,50.750000,6.550000
50%,1.345032e+06,41.500000,56.050000,2.000000,99.500000,4.000000,64.500000,7.700000
75%,1.345046e+06,58.500000,73.950000,3.000000,138.750000,8.000000,87.000000,8.675000
max,1.345061e+06,74.000000,98.400000,3.000000,169.000000,10.000000,98.000000,10.000000

In [10]:
df.describe(include='all')

,Patient ID,Patient\nName,Age,Gender,Disease,Drug\nName,Dosage \nmg,Frequency\nPer Day,Treatment\nDuration Days,Severity \nLevel,Follow \nUp Count,Side \nEffects,Recovery \nRate Percent,Doctor \nRating,Outcome
count,6.000000e+01,60,60.000000,60,60,60,60.000000,60.000000,60.000000,60,60.000000,60,60.000000,60.000000,60
unique,NaN,19,NaN,2,5,10,NaN,NaN,NaN,3,NaN,2,NaN,NaN,3
top,NaN,Vikram,NaN,Male,Migraine,Sumatriptan,NaN,NaN,NaN,Moderate,NaN,Yes,NaN,NaN,Not Recovered
freq,NaN,7,NaN,31,16,11,NaN,NaN,NaN,29,NaN,34,NaN,NaN,25
mean,1.345032e+06,NaN,43.650000,NaN,NaN,NaN,53.170000,1.983333,92.433333,NaN,4.666667,NaN,67.500000,7.630000,NaN
std,1.746425e+01,NaN,17.000324,NaN,NaN,NaN,29.031434,0.812856,50.301588,NaN,3.265986,NaN,19.063231,1.470996,NaN
min,1.345002e+06,NaN,18.000000,NaN,NaN,NaN,2.100000,1.000000,7.000000,NaN,1.000000,NaN,40.000000,5.100000,NaN
25%,1.345017e+06,NaN,28.750000,NaN,NaN,NaN,27.150000,1.000000,46.500000,NaN,1.000000,NaN,50.750000,6.550000,NaN
50%,1.345032e+06,NaN,41.500000,NaN,NaN,NaN,56.050000,2.000000,99.500000,NaN,4.000000,NaN,64.500000,7.700000,NaN
75%,1.345046e+06,NaN,58.500000,NaN,NaN,NaN,73.950000,3.000000,138.750000,NaN,8.000000,NaN,87.000000,8.675000,NaN
max,1.345061e+06,NaN,74.000000,NaN,NaN,NaN,98.400000,3.000000,169.000000,NaN,10.000000,NaN,98.000000,10.000000,NaN

In [11]:
df['Disease'].value_counts()

Disease
Migraine        16
Arthritis       15
Diabetes        13
Hypertension    10
Asthma           6
Name: count, dtype: int64

In [13]:
df['Drug\nName'].value_counts()

Drug\nName
Sumatriptan    11
Ibuprofen       9
Glimepiride     8
Losartan        7
Naproxen        6
Topiramate      5
Metformin       5
Amlodipine      3
Salbutamol      3
Budesonide      3
Name: count, dtype: int64

In [14]:
df['Outcome'].value_counts()

Outcome
Not Recovered    25
Recovered        20
Improving        15
Name: count, dtype: int64

In [15]:
df['Gender'].value_counts()

Gender
Male      31
Female    29
Name: count, dtype: int64

In [16]:
print("Unique Diseases:")

print(df['Disease'].unique())

Unique Diseases:
['Hypertension' 'Migraine' 'Diabetes' 'Arthritis' 'Asthma']

In [18]:
print("Unique Drugs:")

print(df['Drug\nName'].unique())

Unique Drugs:
['Amlodipine' 'Topiramate' 'Metformin' 'Naproxen' 'Losartan' 'Glimepiride'
 'Ibuprofen' 'Sumatriptan' 'Salbutamol' 'Budesonide']

In [20]:
average_recovery = df['Recovery \nRate Percent'].mean()

print("Average Recovery Rate:", average_recovery)

Average Recovery Rate: 67.5

In [22]:
average_duration = df['Treatment\nDuration Days'].mean()

print("Average Treatment Duration:", average_duration)

Average Treatment Duration: 92.43333333333334

In [24]:
print("Total Patients:", len(df))

print("Total Diseases:", df['Disease'].nunique())

print("Total Drugs:", df['Drug\nName'].nunique())

print("Average Recovery Rate:", round(df['Recovery \nRate Percent'].mean(),2))

Total Patients: 60
Total Diseases: 5
Total Drugs: 10
Average Recovery Rate: 67.5